# Generated by Django 5.2.15 on 2026-06-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('severity_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('environmental_risk_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('recommended_action', models.TextField()),
                ('health_risk_summary', models.TextField()),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('_description_encrypted', models.TextField(blank=True, db_column='description_encrypted')),
                ('category', models.CharField(choices=[('plastic_waste', 'Plastic Waste'), ('e_waste', 'E-Waste'), ('water_pollution', 'Water Pollution'), ('open_burning', 'Open Burning'), ('illegal_dumping', 'Illegal Dumping'), ('deforestation', 'Deforestation')], max_length=30)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('image', models.ImageField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
