# Generated by Django 5.2.15 on 2026-06-06 15:10

import security.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalreport',
            name='image',
            field=models.ImageField(upload_to='reports/', validators=[security.validators.validate_image_upload]),
        ),
    ]
