# Generated by Django 5.2.15 on 2026-06-06 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupmission',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleanupmission',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='reports.environmentalreport'),
        ),
        migrations.AddField(
            model_name='cleanupmission',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='joined_missions', to=settings.AUTH_USER_MODEL),
        ),
    ]
